### ISSUE TITLE
investigation on map_update testing report issue upon receiving TCM from geofence  topic

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-stol/carma-platform#1219]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

map_update topic in carma-wm-ctrl  does not publish data upon receiving trafficControlMessage from geofence topic.  Investigation on the below testing data as input to the carma-wm-ctrl module 

### Carma version where this issue was discovered

CARMA version 3.4.1
### Expected behavior

map_update topic in carma-wm-ctrl  shall publish data upon receiving trafficControlMessage from geofence topic.  
### Actual behavior

map_update topic in carma-wm-ctrl  does not publish data upon receiving trafficControlMessage from geofence topic.  
### Steps to reproduce the actual behavior

1. Do this
1. Then do this...
refer to carma installation and development setup to pull/build all carma related images
carma config set <local-image>
carma start all
send below data to /environment/incoming_mobility_operation topic
```
rostopic pub  /message/incoming_mobility_operation cav_msgs/MobilityOperation "header: {sender_id: '', recipient_id: '', senr_bsm_id: '', plan_id: '', timestamp: 0}
strategy: 'carma3/Incident_Use_Case'
strategy_params: 'lat:39.2352,lon:-77.989,downtrack:7,uptrack:6,min_gap:5,advisory_speed:3,event_reason:move over law,event_type:CLOSED'"
```
send below data to /environment/geofence topic
```
rostopic pub /environment/geofence cav_msgs/TrafficControlMessage "choice: 1
tcmV01:
  reqid: {id: [0,0,0,0,0,0,0,0]}
  reqseq: 0
  msgtot: 0
  msgnum: 0
  id: {id: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
  updated: {secs: 0, nsecs: 0}
  package:
    label: 'Move OVER LAW'
    label_exists: false
    tcids:
    - {id: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
  package_exists: false
  params:
    vclasses:
    - {vehicle_class: 0}
    schedule:
      start: {secs: 0, nsecs: 0}
      end: {secs: 0, nsecs: 0}
      end_exists: false
      dow: {dow: [0, 0, 0, 0, 0, 0, 0]}
      dow_exists: false
      between:
      - begin: {secs: 0, nsecs: 0}
        duration: {secs: 0, nsecs: 0}
      between_exists: false
      repeat:
        offset: {secs: 0, nsecs: 0}
        period: {secs: 0, nsecs: 0}
        span: {secs: 0, nsecs: 0}
      repeat_exists: false
    regulatory: false
    detail: {choice: 5, signal: '', closed: 0, chains: 0, direction: 0, lataffinity: 0,
      latperm: [0,0], parking: 0, minspeed: 0.0, maxspeed: 0.0, minhdwy: 0.0, maxvehmass: 0.0,
      maxvehheight: 0.0, maxvehwidth: 0.0, maxvehlength: 0.0, maxvehaxles: 0, minvehocc: 0}
  params_exists: false
  geometry:
    proj: ''
    datum: ''
    reftime: {secs: 0, nsecs: 0}
    reflon: 0.0
    reflat: 0.0
    refelv: 0.0
    heading: 0.0
    nodes:
    - {x: 0.0, y: 0.0, z: 0.0, z_exists: false, width: 0.0, width_exists: false}
  geometry_exists: false"
```
