### ISSUE TITLE
Incorrect parameter file syntax in `pose_to_tf` package

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-platform#1387]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The formatting in the `pose_to_tf` package's `parameters.yaml` file does not use correct YAML file syntax. The file currently looks like
```yaml
child_frame: = "base_link";
default_parent_frame: = "map";
```
The `child_frame` parameter is then incorrectly parsed as `= "base_link";`, which is propagated through to the TF messages. The same holds for the `default_parent_frame` parameter. The correct file should be 
```yaml
child_frame: base_link
default_parent_frame: map
```

### Carma version where this issue was discovered

Affects the `develop`, `noetic/develop`, and `noetic-f1tenth/develop` branches.

### Expected behavior
The parameters should be parsed such that the frame IDs are `base_link` and `map`.

### Actual behavior

The parameters are parsed as `= "base_link";` and `= "map";`.

### Steps to reproduce the actual behavior

1. Launch the CARMA system
2. Echo the `/tf` topic
1. Publish a `geometry_msgs/PoseStamped` message on the `/localization/current_pose` topic with the `map` frame ID
    ```
      seq: 0
      stamp:
        secs: 0
        nsecs: 0
      frame_id: 'map'
    pose:
      position:
        x: 5.0
        y: 0.0
        z: 0.0
      orientation:
        x: 0.9999383
        y: 0.0
        z: 0.0
        w: 0.0111104"
    ```
2. Observe that the resulting transform resembles
    ```
    - 
      header: 
        seq: 1
        stamp: 
          secs: 0
          nsecs:         0
        frame_id: "map"
      child_frame_id: "= \"base_link\";"
      transform: 
        translation: 
          x: 0.0
          y: 0.0
          z: 0.0
        rotation: 
          x: 0.9999383
          y: 0.0
          z: 0.0
          w: 0.0111104
    ```
