### ISSUE TITLE
carma-messenger TCM encoder memory issues

### ISSUE THREAD

**Issue by afrye-leidos** [usdot-fhwa-stol/carma-platform#1763]
### Type of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The carma-messenger TCM encoder has some issues with memory allocation, where some fields get overwritten by others. Testing was done in the develop branch on 5/10/2022, specifically the [testEncodeControlMsg2](https://github.com/usdot-fhwa-stol/carma-messenger/blob/develop/carma-messenger-core/cpp_message/test/test_encode_decode.cpp#L138) test in test_encode_decode of cpp_message. 

Here is a summary of the known issues:
- The first 8 elements of the tcid lists get written as the 8-byte representation of the geometry reftime (1213 turns into [0, 0, 0, 0, 0, 0, 4, 189])
  - This appears to come from the [code where the reftime is stored](https://github.com/usdot-fhwa-stol/carma-messenger/blob/develop/carma-messenger-core/cpp_message/src/cpp_message.cpp#L1156), as when this is commented out the issue disappears. 
- Both 16-element tcid lists are written as the second list
  - In the [code where these are stored](https://github.com/usdot-fhwa-stol/carma-messenger/blob/develop/carma-messenger-core/cpp_message/src/cpp_message.cpp#L1031), the data appears to be stored correctly, but when the second list of tcids is written, they overwrite the first list. 
- The dow field under params/schedule/dow gets written as all 0s
- The nodes under geometry get their z and width fields set to 0

### Carma version where this issue was discovered

carma-messenger develop branch on 5/10/2022

### Expected behavior
Encoding then decoding a message should yield the original message, but it is changed. 

### Actual behavior

When a message is encoded and decoded, certain fields are not the same (described above)

### Steps to reproduce the actual behavior

1. Add code to print out or publish the TCM generated by the [testEncodeControlMsg2](https://github.com/usdot-fhwa-stol/carma-messenger/blob/develop/carma-messenger-core/cpp_message/test/test_encode_decode.cpp#L138) unit test
2. build and test the cpp_message package

Here is a trimmed down message showing which fields change after encoding/decoding:
```
choice: 1
tcm_v01:
  package:
    tcids:
    - id:
      - 0 -> 0
      - 0 -> 0
      - 0 -> 0
      - 0 -> 0
      - 0 -> 0
      - 0 -> 0
      - 0 -> 4
      - 0 -> 189
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
  params:
    schedule:
      dow:
        dow:
        - 1 -> 0
        - 1 -> 0
        - 1 -> 0
        - 1 -> 0
        - 1 -> 0
        - 1 -> 0
        - 1 -> 0
  geometry:
    nodes:
    - x: 1
      y: 1
      z: 1 -> 0
      z_exists: true
      width: 1 -> 0
      width_exists: true
```

### Related work

These issues were found while working on adding fields to the TCM detail message, [CAR-5344](https://usdot-carma.atlassian.net/browse/CAR-5344)
