### ISSUE TITLE
cdasim shouldn't require physical localization nodes 

### ISSUE THREAD

**Issue by MishkaMN** [usdot-fhwa-stol/carma-platform#2168]
### Summary

During testing for VRU use case, it was observed that the ekf_localizer was interfering with the localization/current_pose published by the carla. This resulted in duplicate location data being published by two nodes, one of which had non-simulation timestamp which is incorrect:

```
w: 0.6873035465797234
---
header:
  stamp:
    sec: 233
    nanosec: 217350719
  frame_id: map
pose:
  position:
    x: 145.2482452392578
    y: 224.91566467285156
    z: 0.07448925077915192
  orientation:
    x: -1.1518315547734517e-06
    y: 8.907470606218012e-08
    z: 0.6668391362500139
    w: 0.7452016950893233
---
header:
  stamp:
    sec: 1696459740
    nanosec: 947443019
  frame_id: map
pose:
  position:
    x: 143.83169064804284
    y: 225.242745092671
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.7263703152379856
    w: 0.6873035465797259

```

Resulting error is that the vehicle not able to update its location or gets stuck and don't move
```
[lifecycle_component_wrapper_mt-4]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[carma_component_container_mt-5] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[carma_component_container_mt-5] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[carma_component_container_mt-5]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[carma_component_container_mt-34] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[carma_component_container_mt-34] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[carma_component_container_mt-34]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[carma_component_container_mt-21] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[carma_component_container_mt-21] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[carma_component_container_mt-21]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[carma_component_container_mt-25] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[carma_component_container_mt-25] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[carma_component_container_mt-25]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[carma_component_container_mt-16] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[carma_component_container_mt-16] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[carma_component_container_mt-16]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[carma_component_container_mt-29] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[carma_component_container_mt-29] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[carma_component_container_mt-29]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[lifecycle_component_wrapper_mt-4] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[lifecycle_component_wrapper_mt-4] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[lifecycle_component_wrapper_mt-4]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[lifecycle_component_wrapper_mt-4] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[lifecycle_component_wrapper_mt-4] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[lifecycle_component_wrapper_mt-4]          at line 332 in /tmp/binarydeb/ros-foxy-tf2-0.13.14/src/buffer_core.cpp
[lifecycle_component_wrapper_mt-4] Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 33.197967 according to authority Authority undetectable
[lifecycle_component_wrapper_mt-4] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
```

### Version

4.3.0 (Current)

### Expected Behavior

Vehicle moves without issue

### Actual Behavior

Vehicle doesn't move or jumps location

### Steps to Reproduce the Actual Behavior

carma start all with ekf_localization node running. Without it, it should be fine
